services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80" # Map container's port 80 to host's port 80
    container_name: ecommerce-frontend
    environment:
      - VITE_API_BASE_URL=http://backend:5000/api/ # Use the backend service name as the base URL
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "5000:5000" # Map container's port 5000 to host's port 5000
    container_name: ecommerce-backend
    environment:
      - AWS_REGION=us-east-1               # AWS Region for Secrets Manager
      - ASPNETCORE_ENVIRONMENT=Development # Development environment
    volumes:
      - ~/.aws:/root/.aws:ro               # Mount AWS credentials for the backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
