services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://backend:5000/api/ # Backend service URL for internal Docker network
    ports:
      - "80:80" # Map container's port 80 to host's port 80
    container_name: ecommerce-frontend
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "5000:5000" # Map container's port 5000 to host's port 5000
    container_name: ecommerce-backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - AWS_REGION=us-east-1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
