name: Deploy E-commerce App using CI/CD

on:
  workflow_dispatch: # Manually trigger the workflow from GitHub Actions UI

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH Agent
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # Step 3: Test SSH Connection (Debugging)
      - name: Test SSH Connection
        run: |
          ssh -v -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} exit

      # Step 4: Deploy the Application
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << EOF

            # Prune docker
            docker system prune -af
            sudo apt-get clean
            docker system prune -f
            docker container prune -f
            docker image prune -af
            docker system prune -af --volumes
            docker volume prune -f
            docker network prune -f

            # Add user to the Docker group
            sudo usermod -aG docker ubuntu

            # Restart Docker service (to ensure permissions are applied)
            sudo systemctl restart docker

            # Clone the repository and deploy the application
            if [ ! -d "~/ecommerce-web-app" ]; then
              echo "Cloning repository for the first time"
              git clone -b test https://github.com/Umarsatti1/ecommerce-web-app.git ecommerce-web-app
            fi
            cd ~/ecommerce-web-app
            git fetch origin
            git checkout test
            git reset --hard origin/test
            git clean -fd

            echo "AWS_REGION=${{ secrets.AWS_REGION }}" > .env
            echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" >> .env

            docker-compose down
            docker-compose up --build -d
          EOF
