name: Deploy E-commerce App using CI/CD

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << EOF
            echo "Starting deployment on EC2 instance..."

            sudo apt-get update
            sudo apt-get install -y docker.io docker-compose

            echo "Cleaning up Docker resources..."
            docker system prune -af --volumes || true

            if [ ! -d "~/ecommerce-web-app" ]; then
              git clone -b test https://github.com/Umarsatti1/ecommerce-web-app.git ecommerce-web-app
            fi
            cd ~/ecommerce-web-app
            git fetch origin
            git checkout test
            git reset --hard origin/test
            git clean -fd

            echo "Setting environment variables..."
            echo "AWS_REGION=${{ secrets.AWS_REGION }}" > .env
            echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" >> .env

            docker-compose down || true
            docker-compose up --build -d

            echo "Deployment complete!"
          EOF
